// Generated by AI, welcome to contribute and improve it!
import { useRef } from "react";

export interface ToastOptions {
  content: string;
  duration?: number;
}

class ActionRemoveToast { }
class ActionRedirect2Url {
  url: string;

  constructor(url: string) {
    this.url = url;
  }
}

export const ToastOnclickAction = {
  RemoveToast: ActionRemoveToast,
  Redirect2Url: ActionRedirect2Url
}

const activeToasts: { element: HTMLElement; height: number }[] = [];

const updateToastPositions = () => {
  let accumulatedHeight = 60;
  activeToasts.forEach((toast) => {
    const topPosition = accumulatedHeight;
    toast.element.style.top = `${topPosition}px`;
    accumulatedHeight += toast.height + 10;
  });
};

const removeToast = (toastElement: HTMLElement) => {
  const index = activeToasts.findIndex(t => t.element === toastElement);
  if (index !== -1) {
    toastElement.classList.add('toast-exit');
    activeToasts.splice(index, 1);

    setTimeout(() => {
      toastElement.remove();
      updateToastPositions();
    }, 300);
  }
};

const showToast_ = (
  content: string,
  onClick: ActionRedirect2Url | ActionRemoveToast = new ActionRemoveToast()
) => {
  const toastElement = document.createElement('div');
  toastElement.className = 'toast-notification';
  if (onClick instanceof ActionRedirect2Url) {
    toastElement.style.borderLeft = '2px solid var(--nav-text-color)';
  }
  const parag = document.createElement("p")
  parag.textContent = content
  toastElement.appendChild(parag);

  toastElement.style.opacity = '0';
  toastElement.style.visibility = 'hidden';
  document.body.appendChild(toastElement);

  const height = toastElement.offsetHeight;

  const toastItem = { element: toastElement, height };
  activeToasts.push(toastItem);

  updateToastPositions();

  toastElement.style.opacity = '';
  toastElement.style.visibility = '';
  toastElement.classList.add('toast-enter');

  setTimeout(() => {
    toastElement.classList.remove('toast-enter');
  }, 300);

  const timeoutId = setTimeout(() => {
    removeToast(toastElement);
  }, 2000);

  toastElement.addEventListener('click', () => {
    if (onClick instanceof ActionRedirect2Url) {
      window.open(onClick.url, '_blank');
    } else if (onClick instanceof ActionRemoveToast) {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  });

  return {
    close: () => {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  };
};

export const showToast = {
  nohook: (content: | string, onClick: ActionRedirect2Url | ActionRemoveToast = new ActionRemoveToast()) => {
    let hasShown = false;
    if (!hasShown) {
      hasShown = true;
      showToast_(content, onClick);
    }
  },
  hook: (content: | string, onClick: ActionRedirect2Url | ActionRemoveToast = new ActionRemoveToast()) => {
    let hasShown = useRef<boolean>(false);
    if (!hasShown.current) {
      hasShown.current = true;
      showToast_(content, onClick);
    }
  }
}
