// Generated by AI, welcome to contribute and improve it!
import { useRef } from "react";

export interface ToastOptions {
  content: string;
  duration?: number;
}

class ActionRemoveToast { }
class ActionRedirect2Url {
  url: string;

  constructor(url: string) {
    this.url = url;
  }
}

export const ToastType = {
  Normal: "",
  Info: "info",
  Success: "success",
  Warn: "warn",
  Error: "error",
  Debug: "debug",
} as const;

export type ToastType = typeof ToastType[keyof typeof ToastType];

export const ToastOnclickAction = {
  RemoveToast: ActionRemoveToast,
  Redirect2Url: ActionRedirect2Url
}

const activeToasts: { element: HTMLElement; height: number }[] = [];

const updateToastPositions = () => {
  let accumulatedHeight = 60;
  activeToasts.forEach((toast) => {
    const topPosition = accumulatedHeight;
    toast.element.style.top = `${topPosition}px`;
    accumulatedHeight += toast.height + 10;
  });
};

const removeToast = (toastElement: HTMLElement) => {
  const index = activeToasts.findIndex(t => t.element === toastElement);
  if (index !== -1) {
    toastElement.classList.add('toast-exit');
    activeToasts.splice(index, 1);

    setTimeout(() => {
      toastElement.remove();
      updateToastPositions();
    }, 300);
  }
};

const showToast_ = (
  content: string,
  onClick: ActionRedirect2Url | ActionRemoveToast = new ActionRemoveToast(),
  type: ToastType = ToastType.Normal,
  duration: number = 2000
) => {
  const toastElement = document.createElement('div');
  toastElement.className = 'toast-notification';
  const parag = document.createElement("p")
  parag.textContent = content;
  if (onClick instanceof ActionRedirect2Url) {
    parag.style.textDecoration = 'underline';
    parag.style.textDecorationStyle = 'dotted';
    parag.style.textUnderlineOffset = '4px';
  }
  toastElement.appendChild(parag);

  toastElement.style.setProperty('--toast-duration', `${(duration - 300) / 1000}s`);
  toastElement.style.opacity = '0';
  toastElement.style.visibility = 'hidden';
  document.body.appendChild(toastElement);

  const height = toastElement.offsetHeight;

  const toastItem = { element: toastElement, height };
  activeToasts.unshift(toastItem);

  updateToastPositions();

  toastElement.style.opacity = '';
  toastElement.style.visibility = '';
  toastElement.classList.add('toast-enter');
  if (type != ToastType.Normal) { // 又套了一层判断，烦
    toastElement.classList.add(type);
  }

  setTimeout(() => {
    toastElement.classList.remove('toast-enter');
  }, 300);

  const timeoutId = setTimeout(() => {
    removeToast(toastElement);
  }, duration);

  toastElement.addEventListener('click', () => {
    if (onClick instanceof ActionRedirect2Url) {
      window.open(onClick.url, '_blank');
    } else if (onClick instanceof ActionRemoveToast) {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  });

  return {
    close: () => {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  };
};

export const showToast = {
  nohook: (
    content: string,
    onClick: ActionRedirect2Url | ActionRemoveToast = new ActionRemoveToast(),
    type: ToastType = ToastType.Normal,
    duration: number = 2000
  ) => {
    let hasShown = false;
    if (!hasShown) {
      hasShown = true;
      showToast_(content, onClick, type, duration);
    }
  },
  hook: (
    content: string,
    onClick: ActionRedirect2Url | ActionRemoveToast = new ActionRemoveToast(),
    type: ToastType = ToastType.Normal,
    duration: number = 2000
  ) => {
    let hasShown = useRef<boolean>(false);
    if (!hasShown.current) {
      hasShown.current = true;
      showToast_(content, onClick, type, duration);
    }
  }
}
