// Generated by AI, welcome to contribute and improve it!
import { useRef } from "react";

export interface ToastOptions {
  content: string;
  duration?: number;
}

const activeToasts: { element: HTMLElement; height: number }[] = [];

const updateToastPositions = () => {
  let accumulatedHeight = 60;
  activeToasts.forEach((toast) => {
    const topPosition = accumulatedHeight;
    toast.element.style.top = `${topPosition}px`;
    accumulatedHeight += toast.height + 10;
  });
};

const removeToast = (toastElement: HTMLElement) => {
  const index = activeToasts.findIndex(t => t.element === toastElement);
  if (index !== -1) {
    toastElement.classList.add('toast-exit');
    activeToasts.splice(index, 1);

    setTimeout(() => {
      toastElement.remove();
      updateToastPositions();
    }, 300);
  }
};

const showToast_ = (options: ToastOptions | string) => {
  const { content, duration = 2000 } = typeof options === 'string'
    ? { content: options, duration: 2000 }
    : options;

  const toastElement = document.createElement('div');
  toastElement.className = 'toast-notification';
  toastElement.textContent = content;

  toastElement.style.opacity = '0';
  toastElement.style.visibility = 'hidden';
  document.body.appendChild(toastElement);

  const height = toastElement.offsetHeight;

  const toastItem = { element: toastElement, height };
  activeToasts.push(toastItem);

  updateToastPositions();

  toastElement.style.opacity = '';
  toastElement.style.visibility = '';
  toastElement.classList.add('toast-enter');

  setTimeout(() => {
    toastElement.classList.remove('toast-enter');
  }, 300);

  const timeoutId = setTimeout(() => {
    removeToast(toastElement);
  }, duration);

  toastElement.addEventListener('click', () => {
    clearTimeout(timeoutId);
    removeToast(toastElement);
  });

  return {
    close: () => {
      clearTimeout(timeoutId);
      removeToast(toastElement);
    }
  };
};

export const showToast = {
  nohook: (options: ToastOptions | string) => {
    let hasShown = false;
    if (!hasShown) {
      hasShown = true;
      showToast_(options);
    }
  },
  hook: (options: ToastOptions | string) => {
    let hasShown = useRef<boolean>(false);
    if (!hasShown.current) {
      hasShown.current = true;
      showToast_(options);
    }
  }
}
